add table headers to home page project lists
ucb-rit/coldfront pull request #124
Opened 2021-04-11 16:59 UTC by ViRu-ThE-ViRuS

#108

2021-04-11 18:33 UTC, matthew-li requested changes
This looks great! The compact rows save a lot of space. I had one minor comment on wording for the headers.

2021-04-11 18:33 UTC, matthew-li commented on coldfront/core/portal/templates/portal/authorized_home.html
> +                      <th scope="col" class="text-nowrap">Cluster Access Status</th>
I believe we had wanted to re-use the wording "Project Access on Cluster" from the Project Detail view to be explicit.

2021-04-12 14:22 UTC, ViRu-ThE-ViRuS commented
Thanks! pushing changes

2021-04-12 15:33 UTC, matthew-li approved these changes

2021-04-12 15:33 UTC, merged