add admin view for searching through all users interactively
ucb-rit/coldfront pull request #212
Opened 2021-06-28 13:36 UTC by ViRu-ThE-ViRuS

#201  : added admin view for listing all users

**discussion:**
- filtering through email needs to incorporate multiple email addresses?
- is this to replace `User Search` admin page
- incorporate more filters

2021-06-28 15:06 UTC, matthew-li commented
@ViRu-ThE-ViRuS

> * filtering through email needs to incorporate multiple email addresses?

Yes.

> * is this to replace `User Search` admin page

Let's create a new view. We can then evaluate whether we can hide User Search later.

> * incorporate more filters

A minor one that comes to mind is `middle_name`. Did you have anything else in mind?

2021-06-28 16:47 UTC, ViRu-ThE-ViRuS commented
@matthew-li ready for review!

2021-06-29 20:41 UTC, matthew-li requested changes
This looks and works great! Thanks for getting it in.

I had a few very minor comments.

2021-06-29 20:41 UTC, matthew-li commented on coldfront/core/user/forms.py
> +    email = forms.EmailField(label=EMAIL, max_length=100, required=False)
Thanks for adding support for other email addresses. Let's add a `help_text` field here with the following text:

"You may use this field to find the user that an email address belongs to, even if it is not a primary address."

2021-06-29 20:41 UTC, matthew-li commented on coldfront/core/user/views.py
> +        return self.request.user.is_staff
This should be `is_superuser`. We will open up permissions later once we've reviewed who should get access to what.

2021-06-29 20:41 UTC, matthew-li commented on coldfront/templates/common/navbar_admin.html
> +    <a class="dropdown-item" href="{% url 'user-search-all' %}">All Users</a>
FYI (no action needed): If we wanted this to be available to non-admin staff (which we don't), we'd also want to add this to `navbar_nonadmin_staff.html`.

2021-07-02 08:48 UTC, ViRu-ThE-ViRuS commented
@matthew-li @kmuriki ready for review

2021-07-02 15:12 UTC, matthew-li approved these changes

2021-07-02 15:12 UTC, merged