Issue 167 - export_data management command
ucb-rit/coldfront pull request #358
Opened 2022-02-18 16:21 UTC by jofeinstein

- created new management command `coldfront/core/utils/management/commands/export_data.py`
- There are 4 sub commands: users_who_submitted_jobs, new_cluster_account, job_avg_queue_time, projects

users_who_submitted_jobs:
- returns a list of users who have submitted a job since a given date
- flags:
	- "--format": specifies output file format, either "csv" or "json"
	- "--start_date": date since users last submitted a job
- tests located in `coldfront.core.utils.tests.test_export_data.TestUsersWhoSubmittedJob`

new_cluster_account:
- returns a list of cluster accounts created since a given date
- flags:
	- "--format": specifies output file format, either "csv" or "json"
	- "--start_date": date since cluster account was created
- tests located in `coldfront.core.utils.tests.test_export_data.TestNewClusterAccount`

job_avg_queue_time:
- returns the average queue time for jobs between two dates
- flags:
	- "--start_date": starting date for job submission
	- "--end_date": ending date for job submission
	- "--allowance_type": specify the type of project jobs are associated with
- tests located in `coldfront.core.utils.tests.test_export_data.TestJobAvgQueueTime`

projects:
- returns a list of projects that fit a given filter
- flags:
	- "--format": specifies output file format, either "csv" or "json"
	- "--allowance_type": specify the type of project
	- "--active_only": only output projects with status='Active'
- tests located in `coldfront.core.utils.tests.test_export_data.TestProjects`

2022-02-18 20:09 UTC, matthew-li requested changes
Thanks, both.

I lightly tested these, and the output looks reasonable. I left some comments on things to improve, and some questions.

2022-02-18 20:09 UTC, matthew-li commented on coldfront/core/utils/management/commands/export_data.py
> +        if bool(start_date) ^ bool(end_date):
Wouldn't having either or be fine?

2022-02-22 16:35 UTC, matthew-li commented on coldfront/core/utils/tests/test_export_data.py
> +    def test_users_who_submitted_jobs_json_no_date(self):
The class should be displayed in parentheses after the method name:

```
(venv) [vagrant@vagrant coldfront]$ python manage.py test coldfront.core.project.tests.test_views
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..............................................................................F.......
======================================================================
FAIL: test_fail (coldfront.core.project.tests.test_views.test_project_removal_request_views.TestProjectRemovalRequestListView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/coldfront_app/coldfront/coldfront/core/project/tests/test_views/test_project_removal_request_views.py", line 503, in test_fail
    self.fail('')
AssertionError

----------------------------------------------------------------------
Ran 86 tests in 208.022s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

2022-02-22 17:11 UTC, jofeinstein commented on coldfront/core/utils/tests/test_export_data.py
> +    def test_users_who_submitted_jobs_json_no_date(self):
I must not have seen the "FAIL:" portion

2022-02-23 21:57 UTC, jofeinstein commented
I made the requested changes

2022-02-25 17:09 UTC, matthew-li commented on coldfront/core/utils/tests/test_export_data.py
> +def call_deactivate_command(*args):
Rename this? You could put it under `TestBaseExportData` as `call_command`.

2022-02-25 19:04 UTC, jofeinstein commented
I altered setup in TestBaseExportData so that all the other test classes can use the base class.

2022-02-28 01:06 UTC, ViRu-ThE-ViRuS approved these changes

2022-03-07 18:52 UTC, matthew-li commented
Remaining tasks:
- [ ] Add a `partition` filter for `job_avg_queue_time` (and associated tests).
- [ ] Include PI names and email addresses in the output of `projects`.
- [ ] Add a subcommand for exporting new project requests (and associated tests).

2022-03-07 21:23 UTC, jofeinstein commented
I added filtering on partitions

2022-03-15 20:39 UTC, matthew-li commented
@ViRu-ThE-ViRuS Now would be a good time to fold in the `get_survey_responses` command, as we discussed before.

(Incidentally, the tests for that command are failing on my VMs (not sure about others'); those should get folded into the test suite here.)

2022-03-28 17:11 UTC, matthew-li requested changes
@ViRu-ThE-ViRuS Thanks! I think the last remaining changes are to include the `state` field for `VectorProjectAllocationRequests` and the `extra_fields` field for `SavioProjectAllocationRequests`.

Also, out of curiosity, it looks like `get_survey_responses.py` and its tests got deleted, but they don't appear in the diff in the UI--did you run anything special?

2022-03-29 23:05 UTC, ViRu-ThE-ViRuS commented
pushed the requested changes!

also, idk why its not showing up on the diffs, but it might be because those files exist in `develop` already, and we need to `git rm` them from this branch.

2022-03-30 15:41 UTC, matthew-li reviewed
Thanks for adding those fields; this looks good to go.

But these tests are failing on my box--is it just me?

```
[vagrant@vagrant coldfront]$ python manage.py test coldfront.core.utils.tests.test_export_data
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..................F...FFF
======================================================================
FAIL: test_active_filter (coldfront.core.utils.tests.test_export_data.TestProjects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/coldfront_app/coldfront/coldfront/core/utils/tests/test_export_data.py", line 597, in test_active_filter
    self.assertEqual(str(compare[key]), item[key])
AssertionError: '75' != '84'
- 75
+ 84


======================================================================
FAIL: test_get_survey_responses_allowance_type (coldfront.core.utils.tests.test_export_data.TestSurveyResponses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/coldfront_app/coldfront/coldfront/core/utils/tests/test_export_data.py", line 969, in test_get_survey_responses_allowance_type
    self.assertEquals(project_name, self.filtered_fixtures[index].project.name)
AssertionError: 'fc_test_project3' != 'fc_test_project1'
- fc_test_project3
?                ^
+ fc_test_project1
?                ^


======================================================================
FAIL: test_get_survey_responses_csv (coldfront.core.utils.tests.test_export_data.TestSurveyResponses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/coldfront_app/coldfront/coldfront/core/utils/tests/test_export_data.py", line 951, in test_get_survey_responses_csv
    self.assertEquals(project_name, self.fixtures[index].project.name)
AssertionError: 'test_project2' != 'test_project0'
- test_project2
?             ^
+ test_project0
?             ^


======================================================================
FAIL: test_survey_responses_json (coldfront.core.utils.tests.test_export_data.TestSurveyResponses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/coldfront_app/coldfront/coldfront/core/utils/tests/test_export_data.py", line 933, in test_survey_responses_json
    self.assertEquals(project_name, self.fixtures[index].project.name)
AssertionError: 'fc_test_project3' != 'test_project0'
- fc_test_project3
? ---            ^
+ test_project0
?             ^


----------------------------------------------------------------------
Ran 25 tests in 28.368s

FAILED (failures=4)
Destroying test database for alias 'default'...
```

2022-04-03 22:35 UTC, ViRu-ThE-ViRuS commented
I am getting 3 of these, in test_get_survey_responses, it was because of different sorting in command and test, fixed now. Cannot reproduce `TestProjects.test_active_filters`

2022-04-05 16:00 UTC, jofeinstein commented
The tests all pass locally for me

2022-04-05 16:16 UTC, matthew-li approved these changes

2022-04-05 16:16 UTC, merged