Issue 132b - P2/P3 Adding Users to Secure Directories
ucb-rit/coldfront pull request #397
Opened 2022-04-24 16:04 UTC by jofeinstein

- Created 4 new models in `coldfront/core/allocation/models.py`
    - `SecureDirAddUserRequestStatusChoice, SecureDirAddUserRequest, SecureDirRemoveUserRequestStatusChoice, SecureDirRemoveUserRequest`
- Created 4 new forms in `coldfront/core/allocation/forms_/secure_dir_forms.py`
- Created 5 new views in `coldfront/core/allocation/views_/secure_dir_views.py`
- Added management command `create_directory_defaults`
    - creates objects necessary to store information about secure directories in the database 
- Added 2 new utils in `coldfront/core/allocation/utils.py`
    - create_secure_dir: creates a secure directory attached to the given project with the given subdirectory_name
    - get_secure_dir_manage_user_request_objects: fetches secure directory user management object and stores them in the given object
- Added SecureDirAddUserRequest and SecureDirRemoveUserRequest to the "Request Hub"
- Allocation tab on the navbar is conditionally visible to managers, PIs, staff and admin
    - added allocation_navbar_visibility to `coldfront/core/utils/context_processors.py`

- The way SecureDirAddUserRequest and SecureDirRemoveUserRequest are shown and handled was very similar so the same views handled both
    - For example, `SecureDirManageUsersView` can show either users to add or users to remove
    - Used kwargs in url and get_secure_dir_manage_user_request_objects to fetch relevant objects based on kwargs
    - Similar to how we used a "completed" variable to use the same view to show pending/completed requests

- Added tests for new views and utils
    - views: `python manage.py test coldfront.core.allocation.tests.test_views.test_secure_dir_views`
        - 87% coverage of secure_dir_views.py achieved
        - Mostly missed email exception messages and search filtering conditionals
    - utils: `python manage.py test coldfront.core.allocation.tests.test_utils.test_secure_dir_utils`
        - Near total coverage of 2 new utils. Only error checking not tested.

2022-05-02 16:49 UTC, matthew-li commented
@jofeinstein Is there a way to load in the existing directories (e.g., from a file)? We'll need to do this when deploying to production.

2022-05-02 19:11 UTC, matthew-li requested changes
The core functionality works as expected. Thanks for refactoring where possible and for extensively testing this.

I left mostly minor comments, though PI-handling in `create_secure_dir` might have downstream effects.

I also included `create_directory_defaults` (renamed) in Ansible and merged in `develop`, so you'll need to run the steps in #400 if you haven't already.

2022-05-02 20:22 UTC, jofeinstein commented on coldfront/core/allocation/forms_/secure_dir_forms.py
> +    resource_name = forms.CharField(label='Directory Name',
The way the reset buttons have worked in other search forms is that they just clear what's in the form. You have to press "search" again to get the non-filtered results

2022-05-02 20:25 UTC, jofeinstein commented on coldfront/core/allocation/management/commands/add_directory_defaults.py
> +        from coldfront.core.resource.models import AttributeType
I put the imports inside the code bc there are two types of "AttributeType". One from resource and one from allocation.

2022-05-02 20:45 UTC, jofeinstein commented on coldfront/core/allocation/utils.py
> +    Creates two secure directory allocations: group directory and
I took out the creation of AllocationUsers from the function. We can create a new func when we deal with requests.

2022-05-02 20:49 UTC, jofeinstein commented on coldfront/core/allocation/views_/secure_dir_views.py
> +
Users with view_securediradduserrequest and view_securedirremoveuserrequest can see these. I'll update the staff permissions to include these

2022-05-02 22:07 UTC, jofeinstein commented
I made the requested changes.

2022-05-03 12:38 UTC, jofeinstein commented
I added permissions to the staff group so `python manage.py create_staff_group` will have to be rerun on deployment

2022-05-05 22:35 UTC, matthew-li commented on coldfront/core/allocation/management/commands/add_directory_defaults.py
> +        from coldfront.core.resource.models import AttributeType
Got it--one way to get around this is to `import X as Y`, but this is fine.

2022-05-05 22:53 UTC, matthew-li commented
@jofeinstein Some classes in `secure_dir_views` are missing loggers, causing exceptions when trying to log that a notification email couldn't send.

Would recommend just having one logger at the top-level.

2022-05-05 22:56 UTC, matthew-li commented on coldfront/core/user/templates/request_hub/request_hub.html
>      {% include 'request_hub/request_section.html' %}
Confirmed, thanks.

2022-05-05 22:59 UTC, matthew-li commented
@jofeinstein Thanks for making the changes--things look good now. I ran into one other issue (above). Once resolved, I'll run the test suite and then merge.

Offline, can you provide me with a one-time script to import existing directories and their users? I'll just run it manually as below, since we're not going to need it again.
```
python manage.py shell < your_script_here.py
```

2022-05-09 20:41 UTC, jofeinstein commented
Made the logger changes and I'll get that script to you soon

2022-05-10 15:21 UTC, matthew-li approved these changes
Tests are now passing. Looks good, thanks!

2022-05-10 15:21 UTC, merged