Issue 382 - Added LRC Host User
ucb-rit/coldfront pull request #415
Opened 2022-06-14 20:51 UTC by jofeinstein

- Added functionality that allows non-LBL users to select a host user when joining their first project.
- Addresses [issue_382](https://github.com/ucb-rit/coldfront/issues/382)

Changes

Views:
- `ProjectJoinListView`
	- added dictionary of ProjectSelectHostUserForms to context when eligible users view the page
	- the option to select a host user is only available to users that do not have @lbl.gov emails, do not already have a host user, and have not already made a project join request

- `ProjectJoinView`
	- sets the host user in the ProjectUserJoinRequest if a host user is specified

- `ProjectReviewJoinRequestsView`
	- added a column to the table of join requests that shows if a host user was requested and who was requested to be the host user
	- sets the host user in the user's profile if the project join request is approved

Forms:
- `ProjectSelectHostUserForm`
	- new form to submit if a new user selects a host user when requesting to join a project

Models:
- `ProjectUserJoinRequest`
	- added `host_user` field to the model
- `UserProfile`
	- added `host_user` field to the model

Tests:
- added the following tests: test_project_join_list_view, test_project_join_view, test_project_review_join_requests_view
- all new tests pass locally

2022-06-22 20:20 UTC, matthew-li requested changes
Thanks! The functionality works as expected.

I've left some comments; the important ones are about creating methods for common logic.

2022-06-22 20:20 UTC, matthew-li commented on coldfront/core/project/views.py
> +                and not self.request.user.email.endswith('@lbl.gov') \
The changes in #402 would be affected.

2022-06-23 19:33 UTC, jofeinstein commented on coldfront/core/project/templates/project/project_join_list.html
> +{% if need_host and lrc_only %}
We don't actually need lrc_only here because need_host will only ever be true if LRC_ONLY is enabled

2022-06-23 20:11 UTC, jofeinstein commented
I made the changes and all host_user tests still pass

2022-06-24 03:58 UTC, matthew-li approved these changes

2022-06-24 03:58 UTC, merged