WIP: Issue 337 - Cluster Access API
ucb-rit/coldfront pull request #440
Opened 2022-08-04 18:59 UTC by jofeinstein

**Changes**
- Cluster access was modeled using an `AllocationUserAttribute` with type `Cluster Access Status`. Now use new model `ClusterAccessRequest` and `ClusterAccessRequestStatusChoice`.
- Added new runners `ClusterAccessRequestCompleteRunner` and `ClusterAccessRequestDenialRunner` to handle completing and denying ClusterAccessRequests
   - Runners use new `EmailStrategies` from #437 
- Added new API endpoint for modifying ClusterAccessRequests at `coldfront/api/allocation/views.py`
- Updated request hub to use the new model
- Updated and added tests
- Changes from #437 merged into this branch
   - failing request hub test was fixed

**Testing**
- Note that secure directory tests are failing on this branch but pass on develop

**TODO**
- [ ] Fix comment raised in #337

2022-08-04 19:31 UTC, matthew-li commented
The base branch should be `develop`.

2022-08-04 20:54 UTC, matthew-li requested changes
Thanks for making these changes--I've left some minor comments, but otherwise, the changes look reasonable.

I'll run the test suites and do manual testing afterward.

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/serializers.py
> +            'allocation_user': {'required': True,
Is this already covered by L139?

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/serializers.py
> +        # If the status is being changed to 'Complete', ensure that a
The status in question should be 'Active'.

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/serializers.py
> +            for field in ['completion_time', 'username', 'cluster_uid']:
Is the `for` loop needed? Can we just check each?

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/tests/test_allocation_base.py
> +        call_command('add_default_user_choices')
The second command should already be called by a parent class (`TestAPIBase`). Could the first command be placed there too, and these two removed from here, without issue?

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/views.py
> +                    runner.run(cluster_uid=cluster_uid,
I imagine this works as is, but the parameters are not named, and the arguments are in the wrong order.

2022-08-04 20:54 UTC, matthew-li commented on coldfront/api/allocation/views.py
> +                'Updates one or more fields of the ProjectUserRemovalRequest '
Wrong model.

2022-08-05 17:54 UTC, matthew-li commented on coldfront/core/allocation/management/commands/convert_cluster_attributes_to_cluster_access_request.py
> +"""An admin command that approves AllocationRenewalRequests for a
Copied-and-pasted docstring.

2022-08-07 23:06 UTC, matthew-li commented
@jofeinstein I added a `history` field to `ClusterAccessRequests` in 10cc3b4.

Additionally, I rewrote the conversion command in 87b8674 to:
- Take the date as an input (LRC's is different.)
- Derive request information from the `history` of each `AllocationUserAttribute`. This helps to:
    - Accurately determine when the request was made and completed (it seems like `created` isn't necessarily the most accurate),
    - Allow multiple request flows to be detected and turned into requests (i.e., get added, get removed, then get added again) (although this case probably hasn't arisen),
    - Protect against the edge case wherein an attribute was set to "Denied" because of the user being removed from the project (which we don't want to record as a request), and
    - Allow it to be run multiple times without creating duplicates (nice to have).

Also, we can always reconstruct these requests from the `history`, so if this algorithm isn't perfect (ideally, it would create `HistoricalClusterAccessRequests` with the proper `history_dates`, but that got complicated to implement), it can be improved in the future.

Can you review the changes and test the command? You'll need to un-migrate back to `0010` and then re-migrate (and run `add_allocation_defaults`) first.

2022-08-08 14:15 UTC, jofeinstein commented
The changes make sense and the command still runs. I've never done anything with the history so that was pretty neat.

2022-08-08 15:43 UTC, matthew-li commented
@jofeinstein Thanks for checking. There are some failing tests in `coldfront.api.allocation.tests.allocations.test_cluster_access_request` as a result of the change from "Active" to "Complete", (among other issues, maybe) but other than that, tests are passing.

2022-08-08 16:36 UTC, jofeinstein commented
Test suite passes on my local VM.

2022-08-08 16:39 UTC, merged