WIP: add survey responses to Project detail view
ucb-rit/coldfront pull request #505
Opened 2023-02-03 21:31 UTC by ViRu-ThE-ViRuS

WIP: #394

2023-02-06 17:31 UTC, matthew-li commented
@ViRu-ThE-ViRuS Thanks--can you describe the changes you made in the PR description and include some images of what it looks like here?

2023-02-10 01:15 UTC, ViRu-ThE-ViRuS commented
changes:
- if responses available, add `View` Button for them on Project Detail View. Visible to **EVERYONE**.
- if not available, no changes.

the `View` button will show the responses in an identical POP-UP from `/project/savio-project-completed-request-list/`.

<img width="841" alt="Screenshot 2023-02-09 at 17 10 45" src="https://user-images.githubusercontent.com/16427330/217975484-9fe95aee-98da-485f-816a-adfeea12cde4.png">

<img width="789" alt="Screenshot 2023-02-09 at 17 11 00" src="https://user-images.githubusercontent.com/16427330/217975494-1ed0df5b-664f-49fc-bce5-6ee197cdc055.png">

2023-03-13 16:15 UTC, ViRu-ThE-ViRuS commented
updated:
![screenshot_2023-03-11_at_22 44 24_720](https://user-images.githubusercontent.com/16427330/224761579-99d9ee84-e1fc-4bf9-a4ad-141da21f6c96.png)

ready for review.

2023-03-22 16:42 UTC, matthew-li requested changes
Thanks for adding this. It behaves as expected during manual testing.

I added some comments about request filtering/ordering and some minor refactoring that could be done.

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/templates/project/project_request/savio/project_request_surveys_modal.html
> +            {% if forloop.counter == 1 %}
This block could be refactored to the below to minimize duplication:

```
            <li id="survey-nav-item" class="nav-item">
              <a data-toggle="tab" class="nav-link{% if forloop.counter == 1 %} active{% endif %}" href="#survey{{forloop.counter}}">
                Survey #{{forloop.counter}}
              </a>
            </li>
```

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/templates/project/project_request/savio/project_request_surveys_modal.html
> +            {% if forloop.counter == 1 %}
See the above comment to use `active` or `fade` based on the conditional.

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/views.py
> +        allocation_requests = SavioProjectAllocationRequest.objects.filter(project=self.object)
This `filter` call is being made twice--you can get them all above and then use `.exists()` to check if any exist before iterating over them in the `lambda` below.

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/views.py
> +        allocation_request = SavioProjectAllocationRequest.objects.filter(
Only requests with the "Approved - Complete" status should be included. (We don't want to include surveys from denied or pending requests.)

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/views.py
> +        allocation_request = SavioProjectAllocationRequest.objects.filter(
Also, let's sort the requests so that earlier ones appear first (Survey 1 is earliest).

`.order_by('request_time')`

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/templates/project/project_request/savio/project_request_surveys_modal.html
> +                    <p class="card-text"><b>Requester:</b> {{ allocation_request.requester }} </p>
For "Requester" and "Principal Investigator", display: "First Last (username)":

`{{ user.first_name }} {{ user.last_name }} ({{ user.username }})`

2023-03-22 16:42 UTC, matthew-li commented on coldfront/core/project/views.py
> +        survey_answers_list = list(map(lambda x: SavioProjectSurveyForm(initial=x.survey_answers, disable_fields=True), allocation_requests))
Limit lines to ~80 characters when possible.

2023-04-03 08:34 UTC, ViRu-ThE-ViRuS commented
thanks for the review!
missed some silly things, thats on me : /

2023-04-19 16:14 UTC, matthew-li approved these changes
Thanks, LGTM now. Merging.

2023-04-19 16:14 UTC, merged