Issue 519
ucb-rit/coldfront pull request #520
Opened 2023-03-23 23:38 UTC by ViRu-ThE-ViRuS

#519 

**TODOs:**
- [x]  Update HTML files referenced by RequestListItems in request_hub_views.py so that the sorting icons are replaced with an include tag. See project_removal_request_list_table.html for an example.
- [x]  Verify that sorting still works across these pages.
- [x]  Re-order requests so that later ones appear first initially in the request hub. Either use a relevant time field, or ID.
- [x]  Re-order these requests in their respective dedicated views as well, using the same sorting field.

2023-03-31 18:44 UTC, matthew-li requested changes
Thanks. The changes look reasonable, but I ran into some errors during testing.

Can you take a pass over the various views to ensure that sorting behaves as expected and doesn't raise an error?

2023-03-31 18:44 UTC, matthew-li commented on coldfront/core/project/templates/project/project_renewal/project_renewal_request_list_table.html
>    <tr>
I'm seeing an error trying to sort on "Project". This is the case on production too.

2023-04-10 05:58 UTC, ViRu-ThE-ViRuS commented on coldfront/core/project/templates/project/project_request/savio/project_request_list_table.html
>    <tr>
it was because passing `table_sorter_field='pi'` wasn't sorting by default on `pi__email`. fixed.

2023-04-10 06:09 UTC, ViRu-ThE-ViRuS commented on coldfront/core/project/templates/project/project_request/savio/project_request_list_table.html
>    <tr>
fixed the same issue in `../vector/project_request_list_table.html`

2023-04-10 06:11 UTC, ViRu-ThE-ViRuS commented
ready for review!

2023-04-19 16:22 UTC, matthew-li approved these changes
Thanks, all my comments have been resolved.

2023-04-19 16:22 UTC, merged