Issue 521: Docker Support
ucb-rit/coldfront pull request #522
Opened 2023-03-28 22:01 UTC by Hzaakk

Adding `Dockerfile` and `docker-compose.yml` inside a new `docker/` directory

How to use:
1. Build Image: In base directory, run `docker build . -f docker/Dockerfile -t coldfront`
2. To run: In base directory, run `docker compose -f docker/docker-compose.yml up`
3. To start from scratch (delete volumes): In base directory, run `docker compose -f docker/docker-compose.yml down --volumes`

2023-04-10 16:57 UTC, matthew-li commented
@Hzaakk

@ViRu-ThE-ViRuS wants to know how big the image sizes are, due to limited disk space--can you list those here?

2023-04-17 00:07 UTC, ViRu-ThE-ViRuS commented
> @ViRu-ThE-ViRuS wants to know how big the image sizes are, due to limited disk space--can you list those here?
image size on Mac: 1.22GB

2023-04-19 17:17 UTC, matthew-li requested changes
Great job--this worked for me. I left some minor comments.

2023-04-19 17:17 UTC, matthew-li commented on Dockerfile
> +ARG base_dir="/vagrant/coldfront_app"
This path is hardcoded in a volume in `docker-compose.yml` but configurable here. I'd say we can keep it hardcoded.

2023-05-01 16:14 UTC, merged