Issue 571: Adding unit testing for export_data renewal_survey_answers command
ucb-rit/coldfront pull request #603
Opened 2024-05-16 18:44 UTC by haudquaquam

**Changes**

- Added `TestRenewalSurveyResponses` in `coldfront.core.utils.tests.test_export_data.py`
  - 3 tests: JSON, CSV, allowance type
  - Uses the following hardcoded elements:
    - Hardcoded renewal survey with sample answers for BRC version of `ProjectRenewalSurveyForm`
    - `Allowance Year 2024 - 2025`
    - CSV test uses question 6 from the renewal survey

**Testing**

- Within `app-shell`, run the following: `python3 manage.py test coldfront.core.utils.tests.test_export_data.TestRenewalSurveyResponses`

2024-05-20 17:30 UTC, matthew-li requested changes
Thanks, these are passing for me and overall look fine. I left a few comments about code style.

2024-05-20 17:30 UTC, matthew-li commented on coldfront/core/utils/tests/test_export_data.py
> +            pi = User.objects.create(
Is this needed? Looks like the `pi` variable is getting replaced later.

2024-05-20 17:30 UTC, matthew-li commented on coldfront/core/utils/tests/test_export_data.py
> +            renewal_survey = {
We tend to use single quotes across the codebase (though it's not entirely consistent).

Also, can you ensure that lines are (generally) <= 80 characters?

2024-05-20 17:30 UTC, matthew-li commented on coldfront/core/utils/tests/test_export_data.py
> +                if question in multiple_choice_fields.keys():
Too much indentation.

2024-05-20 22:13 UTC, haudquaquam commented
Thank you @matthew-li, I addressed your comments.

2024-05-21 16:05 UTC, matthew-li approved these changes

2024-05-21 16:06 UTC, merged