WIP: Issue 73
ucb-rit/coldfront pull request #81
Opened 2021-03-24 13:57 UTC by ViRu-ThE-ViRuS

#73 

### changes made
- users cannot `Join a project` unless they have signed the user agreement

2021-03-25 03:13 UTC, matthew-li requested changes
Thanks for working on this--the changes look good! I think there's one case not being handled, which I mentioned in the comments.

Also, @kmuriki, should we prevent project managers from adding a user to their project (via the "Add Users" button) until that user has signed the agreement? Maybe we can display the user as grayed out, and write some explanatory text at the top saying that grayed out users need to sign the agreement first. What do you think?

2021-03-25 03:13 UTC, matthew-li commented on coldfront/core/project/templates/project/project_list.html
> +        Join a project
Minor styling issue: let's retain the icon from the active case.

2021-03-25 03:13 UTC, matthew-li commented on coldfront/core/project/views.py
> +class ProjectJoinListView(ProjectListView, UserPassesTestMixin):
This looks good. We should also block `ProjectJoinView` similarly.

2021-03-25 03:41 UTC, kmuriki commented
Yes greying out unsigned users for adding to a project to the PI sounds great!

2021-03-25 15:53 UTC, ViRu-ThE-ViRuS commented
Ready for review!

2021-03-25 23:15 UTC, matthew-li requested changes
Thanks for adding the blocks. Can you also add the following explanation somewhere on the "Add Users" view?

> You may only add users who have signed the access agreement.

2021-03-29 17:11 UTC, matthew-li approved these changes
I've added the text, since it was a quick addition, and resolved some merge conflicts. Thanks again!

2021-03-29 17:11 UTC, merged